server:
  port: ${SERVER_PORT:${PORT:8080}}
  forward-headers-strategy: framework

spring:
  application:
    name: dist-api-gateway
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

app:
  gateway:
    target-base-url: ${APP_GATEWAY_BUSINESS_QR_URL:${APP_GATEWAY_TARGET_BASE_URL:http://localhost:8081}}

management:
  endpoints:
    web:
      exposure:
        include: health, info
